#############################################################################
# Makefile for building: SkittleToo
# Generated by qmake (2.01a) (Qt 4.6.2) on: Wed Mar 9 01:51:57 2011
# Project:  SkittleToo.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile SkittleToo.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I. -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = AbstractGraph.cpp \
		AlignmentDisplay.cpp \
		AnnotationDisplay.cpp \
		ColorListEditor.cpp \
		CylinderDisplay.cpp \
		NucleotideLinker.cpp \
		FastaReader.cpp \
		FrequencyMap.cpp \
		glwidget.cpp \
		GtfReader.cpp \
		HighlightDisplay.cpp \
		main.cpp \
		MainWindow.cpp \
		MdiChildWindow.cpp \
		NucleotideDisplay.cpp \
		OligomerDisplay.cpp \
		SequenceEntry.cpp \
		TextureCanvas.cpp \
		UiVariables.cpp \
		ViewManager.cpp moc_AbstractGraph.cpp \
		moc_AlignmentDisplay.cpp \
		moc_AnnotationDisplay.cpp \
		moc_ColorListEditor.cpp \
		moc_CylinderDisplay.cpp \
		moc_FastaReader.cpp \
		moc_FrequencyMap.cpp \
		moc_glwidget.cpp \
		moc_GtfReader.cpp \
		moc_HighlightDisplay.cpp \
		moc_MainWindow.cpp \
		moc_MdiChildWindow.cpp \
		moc_NucleotideDisplay.cpp \
		moc_OligomerDisplay.cpp \
		moc_SequenceEntry.cpp \
		moc_ViewManager.cpp \
		moc_UiVariables.cpp \
		qrc_resources.cpp
OBJECTS       = AbstractGraph.o \
		AlignmentDisplay.o \
		AnnotationDisplay.o \
		ColorListEditor.o \
		CylinderDisplay.o \
		NucleotideLinker.o \
		FastaReader.o \
		FrequencyMap.o \
		glwidget.o \
		GtfReader.o \
		HighlightDisplay.o \
		main.o \
		MainWindow.o \
		MdiChildWindow.o \
		NucleotideDisplay.o \
		OligomerDisplay.o \
		SequenceEntry.o \
		TextureCanvas.o \
		UiVariables.o \
		ViewManager.o \
		moc_AbstractGraph.o \
		moc_AlignmentDisplay.o \
		moc_AnnotationDisplay.o \
		moc_ColorListEditor.o \
		moc_CylinderDisplay.o \
		moc_FastaReader.o \
		moc_FrequencyMap.o \
		moc_glwidget.o \
		moc_GtfReader.o \
		moc_HighlightDisplay.o \
		moc_MainWindow.o \
		moc_MdiChildWindow.o \
		moc_NucleotideDisplay.o \
		moc_OligomerDisplay.o \
		moc_SequenceEntry.o \
		moc_ViewManager.o \
		moc_UiVariables.o \
		qrc_resources.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		SkittleToo.pro
QMAKE_TARGET  = SkittleToo
DESTDIR       = 
TARGET        = SkittleToo

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_BookmarkDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SkittleToo.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile SkittleToo.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile SkittleToo.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SkittleToo1.0.0 || $(MKDIR) .tmp/SkittleToo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SkittleToo1.0.0/ && $(COPY_FILE) --parents AbstractGraph.h AlignmentDisplay.h AnnotationDisplay.h BasicTypes.h ui_BookmarkDialog.h ColorListEditor.h CylinderDisplay.h FastaReader.h FrequencyMap.h glwidget.h GtfReader.h HighlightDisplay.h MainWindow.h MdiChildWindow.h NucleotideDisplay.h NucleotideLinker.h NucleotideLink.h OligomerDisplay.h SequenceEntry.h TextureCanvas.h ViewManager.h UiVariables.h .tmp/SkittleToo1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/SkittleToo1.0.0/ && $(COPY_FILE) --parents AbstractGraph.cpp AlignmentDisplay.cpp AnnotationDisplay.cpp ColorListEditor.cpp CylinderDisplay.cpp NucleotideLinker.cpp FastaReader.cpp FrequencyMap.cpp glwidget.cpp GtfReader.cpp HighlightDisplay.cpp main.cpp MainWindow.cpp MdiChildWindow.cpp NucleotideDisplay.cpp OligomerDisplay.cpp SequenceEntry.cpp TextureCanvas.cpp UiVariables.cpp ViewManager.cpp .tmp/SkittleToo1.0.0/ && $(COPY_FILE) --parents BookmarkDialog.ui .tmp/SkittleToo1.0.0/ && (cd `dirname .tmp/SkittleToo1.0.0` && $(TAR) SkittleToo1.0.0.tar SkittleToo1.0.0 && $(COMPRESS) SkittleToo1.0.0.tar) && $(MOVE) `dirname .tmp/SkittleToo1.0.0`/SkittleToo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SkittleToo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_AbstractGraph.cpp moc_AlignmentDisplay.cpp moc_AnnotationDisplay.cpp moc_ColorListEditor.cpp moc_CylinderDisplay.cpp moc_FastaReader.cpp moc_FrequencyMap.cpp moc_glwidget.cpp moc_GtfReader.cpp moc_HighlightDisplay.cpp moc_MainWindow.cpp moc_MdiChildWindow.cpp moc_NucleotideDisplay.cpp moc_OligomerDisplay.cpp moc_SequenceEntry.cpp moc_ViewManager.cpp moc_UiVariables.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_AbstractGraph.cpp moc_AlignmentDisplay.cpp moc_AnnotationDisplay.cpp moc_ColorListEditor.cpp moc_CylinderDisplay.cpp moc_FastaReader.cpp moc_FrequencyMap.cpp moc_glwidget.cpp moc_GtfReader.cpp moc_HighlightDisplay.cpp moc_MainWindow.cpp moc_MdiChildWindow.cpp moc_NucleotideDisplay.cpp moc_OligomerDisplay.cpp moc_SequenceEntry.cpp moc_ViewManager.cpp moc_UiVariables.cpp
moc_AbstractGraph.cpp: BasicTypes.h \
		TextureCanvas.h \
		AbstractGraph.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) AbstractGraph.h -o moc_AbstractGraph.cpp

moc_AlignmentDisplay.cpp: BasicTypes.h \
		UiVariables.h \
		AbstractGraph.h \
		TextureCanvas.h \
		AlignmentDisplay.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) AlignmentDisplay.h -o moc_AlignmentDisplay.cpp

moc_AnnotationDisplay.cpp: BasicTypes.h \
		AbstractGraph.h \
		TextureCanvas.h \
		UiVariables.h \
		AnnotationDisplay.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) AnnotationDisplay.h -o moc_AnnotationDisplay.cpp

moc_ColorListEditor.cpp: ColorListEditor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ColorListEditor.h -o moc_ColorListEditor.cpp

moc_CylinderDisplay.cpp: BasicTypes.h \
		AbstractGraph.h \
		TextureCanvas.h \
		UiVariables.h \
		NucleotideLinker.h \
		NucleotideLink.h \
		CylinderDisplay.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) CylinderDisplay.h -o moc_CylinderDisplay.cpp

moc_FastaReader.cpp: FastaReader.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) FastaReader.h -o moc_FastaReader.cpp

moc_FrequencyMap.cpp: BasicTypes.h \
		AbstractGraph.h \
		TextureCanvas.h \
		NucleotideDisplay.h \
		UiVariables.h \
		FrequencyMap.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) FrequencyMap.h -o moc_FrequencyMap.cpp

moc_glwidget.cpp: BasicTypes.h \
		UiVariables.h \
		glwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) glwidget.h -o moc_glwidget.cpp

moc_GtfReader.cpp: BasicTypes.h \
		UiVariables.h \
		GtfReader.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) GtfReader.h -o moc_GtfReader.cpp

moc_HighlightDisplay.cpp: NucleotideDisplay.h \
		BasicTypes.h \
		AbstractGraph.h \
		TextureCanvas.h \
		UiVariables.h \
		HighlightDisplay.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) HighlightDisplay.h -o moc_HighlightDisplay.cpp

moc_MainWindow.cpp: UiVariables.h \
		MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MainWindow.h -o moc_MainWindow.cpp

moc_MdiChildWindow.cpp: UiVariables.h \
		MdiChildWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MdiChildWindow.h -o moc_MdiChildWindow.cpp

moc_NucleotideDisplay.cpp: BasicTypes.h \
		AbstractGraph.h \
		TextureCanvas.h \
		UiVariables.h \
		NucleotideDisplay.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) NucleotideDisplay.h -o moc_NucleotideDisplay.cpp

moc_OligomerDisplay.cpp: BasicTypes.h \
		FrequencyMap.h \
		AbstractGraph.h \
		TextureCanvas.h \
		NucleotideDisplay.h \
		UiVariables.h \
		OligomerDisplay.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) OligomerDisplay.h -o moc_OligomerDisplay.cpp

moc_SequenceEntry.cpp: ColorListEditor.h \
		BasicTypes.h \
		SequenceEntry.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) SequenceEntry.h -o moc_SequenceEntry.cpp

moc_ViewManager.cpp: MdiChildWindow.h \
		UiVariables.h \
		ViewManager.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ViewManager.h -o moc_ViewManager.cpp

moc_UiVariables.cpp: UiVariables.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) UiVariables.h -o moc_UiVariables.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		zoomIn.png \
		zoomOut.png \
		skittle.svg \
		zoomIn-mask.png
	/usr/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_BookmarkDialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_BookmarkDialog.h
ui_BookmarkDialog.h: BookmarkDialog.ui
	/usr/bin/uic-qt4 BookmarkDialog.ui -o ui_BookmarkDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

AbstractGraph.o: AbstractGraph.cpp AbstractGraph.h \
		BasicTypes.h \
		TextureCanvas.h \
		UiVariables.h \
		glwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AbstractGraph.o AbstractGraph.cpp

AlignmentDisplay.o: AlignmentDisplay.cpp AlignmentDisplay.h \
		BasicTypes.h \
		UiVariables.h \
		AbstractGraph.h \
		TextureCanvas.h \
		glwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AlignmentDisplay.o AlignmentDisplay.cpp

AnnotationDisplay.o: AnnotationDisplay.cpp AnnotationDisplay.h \
		BasicTypes.h \
		AbstractGraph.h \
		TextureCanvas.h \
		UiVariables.h \
		glwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AnnotationDisplay.o AnnotationDisplay.cpp

ColorListEditor.o: ColorListEditor.cpp ColorListEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ColorListEditor.o ColorListEditor.cpp

CylinderDisplay.o: CylinderDisplay.cpp CylinderDisplay.h \
		BasicTypes.h \
		AbstractGraph.h \
		TextureCanvas.h \
		UiVariables.h \
		NucleotideLinker.h \
		NucleotideLink.h \
		glwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CylinderDisplay.o CylinderDisplay.cpp

NucleotideLinker.o: NucleotideLinker.cpp NucleotideLinker.h \
		NucleotideLink.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NucleotideLinker.o NucleotideLinker.cpp

FastaReader.o: FastaReader.cpp FastaReader.h \
		BasicTypes.h \
		glwidget.h \
		UiVariables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FastaReader.o FastaReader.cpp

FrequencyMap.o: FrequencyMap.cpp FrequencyMap.h \
		BasicTypes.h \
		AbstractGraph.h \
		TextureCanvas.h \
		NucleotideDisplay.h \
		UiVariables.h \
		glwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FrequencyMap.o FrequencyMap.cpp

glwidget.o: glwidget.cpp glwidget.h \
		BasicTypes.h \
		UiVariables.h \
		NucleotideDisplay.h \
		AbstractGraph.h \
		TextureCanvas.h \
		FrequencyMap.h \
		AnnotationDisplay.h \
		CylinderDisplay.h \
		NucleotideLinker.h \
		NucleotideLink.h \
		AlignmentDisplay.h \
		OligomerDisplay.h \
		HighlightDisplay.h \
		GtfReader.h \
		FastaReader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o glwidget.cpp

GtfReader.o: GtfReader.cpp GtfReader.h \
		BasicTypes.h \
		UiVariables.h \
		NucleotideDisplay.h \
		AbstractGraph.h \
		TextureCanvas.h \
		ui_BookmarkDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GtfReader.o GtfReader.cpp

HighlightDisplay.o: HighlightDisplay.cpp HighlightDisplay.h \
		NucleotideDisplay.h \
		BasicTypes.h \
		AbstractGraph.h \
		TextureCanvas.h \
		UiVariables.h \
		glwidget.h \
		SequenceEntry.h \
		ColorListEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HighlightDisplay.o HighlightDisplay.cpp

main.o: main.cpp MainWindow.h \
		UiVariables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		UiVariables.h \
		FastaReader.h \
		GtfReader.h \
		BasicTypes.h \
		glwidget.h \
		AbstractGraph.h \
		TextureCanvas.h \
		NucleotideDisplay.h \
		FrequencyMap.h \
		AnnotationDisplay.h \
		CylinderDisplay.h \
		NucleotideLinker.h \
		NucleotideLink.h \
		AlignmentDisplay.h \
		OligomerDisplay.h \
		HighlightDisplay.h \
		ViewManager.h \
		MdiChildWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

MdiChildWindow.o: MdiChildWindow.cpp MdiChildWindow.h \
		UiVariables.h \
		glwidget.h \
		BasicTypes.h \
		HighlightDisplay.h \
		NucleotideDisplay.h \
		AbstractGraph.h \
		TextureCanvas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MdiChildWindow.o MdiChildWindow.cpp

NucleotideDisplay.o: NucleotideDisplay.cpp NucleotideDisplay.h \
		BasicTypes.h \
		AbstractGraph.h \
		TextureCanvas.h \
		UiVariables.h \
		glwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NucleotideDisplay.o NucleotideDisplay.cpp

OligomerDisplay.o: OligomerDisplay.cpp OligomerDisplay.h \
		BasicTypes.h \
		FrequencyMap.h \
		AbstractGraph.h \
		TextureCanvas.h \
		NucleotideDisplay.h \
		UiVariables.h \
		glwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OligomerDisplay.o OligomerDisplay.cpp

SequenceEntry.o: SequenceEntry.cpp SequenceEntry.h \
		ColorListEditor.h \
		BasicTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SequenceEntry.o SequenceEntry.cpp

TextureCanvas.o: TextureCanvas.cpp TextureCanvas.h \
		BasicTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextureCanvas.o TextureCanvas.cpp

UiVariables.o: UiVariables.cpp UiVariables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UiVariables.o UiVariables.cpp

ViewManager.o: ViewManager.cpp ViewManager.h \
		MdiChildWindow.h \
		UiVariables.h \
		glwidget.h \
		BasicTypes.h \
		HighlightDisplay.h \
		NucleotideDisplay.h \
		AbstractGraph.h \
		TextureCanvas.h \
		GtfReader.h \
		MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ViewManager.o ViewManager.cpp

moc_AbstractGraph.o: moc_AbstractGraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AbstractGraph.o moc_AbstractGraph.cpp

moc_AlignmentDisplay.o: moc_AlignmentDisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AlignmentDisplay.o moc_AlignmentDisplay.cpp

moc_AnnotationDisplay.o: moc_AnnotationDisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AnnotationDisplay.o moc_AnnotationDisplay.cpp

moc_ColorListEditor.o: moc_ColorListEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ColorListEditor.o moc_ColorListEditor.cpp

moc_CylinderDisplay.o: moc_CylinderDisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CylinderDisplay.o moc_CylinderDisplay.cpp

moc_FastaReader.o: moc_FastaReader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FastaReader.o moc_FastaReader.cpp

moc_FrequencyMap.o: moc_FrequencyMap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FrequencyMap.o moc_FrequencyMap.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

moc_GtfReader.o: moc_GtfReader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GtfReader.o moc_GtfReader.cpp

moc_HighlightDisplay.o: moc_HighlightDisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HighlightDisplay.o moc_HighlightDisplay.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_MdiChildWindow.o: moc_MdiChildWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MdiChildWindow.o moc_MdiChildWindow.cpp

moc_NucleotideDisplay.o: moc_NucleotideDisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NucleotideDisplay.o moc_NucleotideDisplay.cpp

moc_OligomerDisplay.o: moc_OligomerDisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_OligomerDisplay.o moc_OligomerDisplay.cpp

moc_SequenceEntry.o: moc_SequenceEntry.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SequenceEntry.o moc_SequenceEntry.cpp

moc_ViewManager.o: moc_ViewManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ViewManager.o moc_ViewManager.cpp

moc_UiVariables.o: moc_UiVariables.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_UiVariables.o moc_UiVariables.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

